// VLAB global definitions

HQ_BRANCH = "HQ";

FOLDER_DRAFT = "DRAFT";
FOLDER_COMMIT = "COMMIT";
FOLDER_WIP = "WIP";
FOLDER_APPROVAL = "APPR";
FOLDER_DONE = "DONE";


REDTEXTSTYLE = "color:#E51B0F";
LISTPOBACKGROUND = "background:#E8C61F";

